#!/usr/bin/env python

import sys
import base64
import hmac, hashlib

from jinja2 import Template

if len(sys.argv) != 4:
    print 'usage: ' + sys.argv[0] + ' <AWS_ACCESS_KEY> <AWS_SECRET_ACCESS_KEY> <bucket_name>'
    sys.exit()

AWS_ACCESS_KEY = sys.argv[1]
AWS_SECRET_ACCESS_KEY = sys.argv[2]
BUCKET = sys.argv[3]

with open('policy_doc.json', 'r') as policy_f:
    policy = base64.b64encode(policy_f.read())
    signature = base64.b64encode(hmac.new(AWS_SECRET_ACCESS_KEY, policy, hashlib.sha1).digest())

    with open('template.index.html') as template_f:
        template = Template(template_f.read())
        tmp = template.render(
                            bucket=BUCKET,
                            signature=signature,
                            policy=policy,
                            aws_key=AWS_ACCESS_KEY)
        print tmp
